"""add verify for user

Revision ID: 5734ae8982ff
Revises: f8f25c52265b
Create Date: 2023-12-25 14:03:03.221477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5734ae8982ff'
down_revision: Union[str, None] = 'f8f25c52265b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', sa.Enum('admin', 'moderator', 'user', name='role'), nullable=True))
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
